### ISSUE TITLE
Update to Node 16

### ISSUE THREAD

**Issue by mihaitodor** [gha-utilities/sass-build#304]
According to the GitHub blog, Node 12 has been deprecated on September 27th 2022: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Would you be open to updating `action.yml` as described [here](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-nodejs-v16)?

**Comment by S0AndS0** [comment]
Thanks for the heads-up, and relevant links!

I've adjusted the targeted Node version to `16`, but am refraining from tagging a new version of this project until I read back from anyone using this Action.

If ya have a chance to test changes I'd certainly appreciate it, eg.

```YAML
# ...
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@5100f7b0efc3128968365f145fb324b6ed5176e4
        with:
          source: ./_scss/main.scss
          destination: ./assets/css/main.css
          source_map: true
# ...
```
